version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  aws-ebcli: circleci/aws-elastic-beanstalk@2.0.1
  aws-s3cli: circleci/aws-s3@3.0.0
jobs:
  deployment:
    docker:
      - image: cimg/node:16.10
      - image: circleci/node:8-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-ebcli/setup
      - run:
          name: Back-End install
          command: npm run backend:install
      - run:
          name: Front-End install
          command: npm run frontend:install
      - run:
          name: Back-End test
          command: npm run backend:test
      - run:
          name: Front-End test
          command: npm run frontend:test
      - run:
          name: Back-End build
          command: npm run backend:build
      - run:
          name: Front-End build
          command: npm run frontend:build
      - run:
          name: Back-End deploy
          command: npm run backend:deploy
      - run:
          name: Front-End deploy
          command: npm run frontend:deploy
workflows:
  deploy:
    jobs:
      - deployment
